### ISSUE TITLE
Issue with AST_05, 07 and 08

### ISSUE THREAD

**Issue by eMandanici** [dawhite/APTK#5] opened 2024-07-29 16:44 UTC
I am using APTK 1.1.2 on ENVI 6.0. When opening some AST_05, AST_07 and AST_08 products and providing the corresponding L1A to generate RPCs, I get the error "Attempt to subscript COEFFS with <LONG  (    1)> is out of range" and ENVI crashes. 

This is the metadata of the 05 and L1A products: [metadata.zip](https://github.com/user-attachments/files/16416318/metadata.zip)

Can you give me a suggestion?

Thanks.

**Comment by dawhite** [comment] 2024-07-30 02:13
Thank you for providing the metadata--it really helps. To ensure a clean test, I downloaded the AST_05 file and corresponding AST_L1A file directly from NASA Earth Data and inputted them into APTK 1.1.2 running under ENVI 5.0 (the latest version I have right now) in Classic mode. The AST_05 file converted successfully. See screenshots below. 

The first thing I would try is to redownload the two HDF files and run them through APTK again. I would also ensure that APTK is installed correctly: delete the APTK folder, install a fresh copy, then restart ENVI. If APTK fails, try 6.0 in Classic mode (requires installing the APTK folder in save_add instead of extensions). If it still fails, try ENVI 5.0 instead of 6.0. Your license will permit you to install previous versions. If it works in 5.0, then I think there is a 6.0 compatibility issue of some kind. That would be weird, but is possible. I would have to work with the ENVI folks to get a license for 6.0 to look into the issue.

Another thing to check is if APTK is actually outputting the correct information but ENVI is not handling it well. Go to the folder where you are outputting the converted AST_05 file and open the .hdr file in a text editor. You should see a block of text that starts with "rpc_info = {" if the conversion was successful. Mine looks like this:

> rpc info = {
>   3.50000000e+002,  4.15000000e+002,  4.19662000e+001, -1.18220700e+002,
>   1.97000000e+003,  3.50000000e+002,  4.15000000e+002,  3.46100000e-001,
>   5.19900000e-001,  5.74000000e+002,  1.38032359e-003, -2.76729132e-001,
>  -1.19482398e+000, -5.15185611e-005,  1.62575270e-003, -6.94683768e-007,
>  -2.06862601e-007, -4.04963130e-003, -4.68396121e-005,  3.65223154e-009,
>  -1.78501948e-007,  1.35174418e-007,  4.35062875e-006, -1.14639453e-010,
>  -5.50879336e-006,  5.18504188e-007, -1.85795397e-010,  1.15234532e-007,
>   7.46078915e-008, -7.74568268e-013,  1.00000000e+000,  2.00550848e-008,
>  -2.24063448e-008, -2.31870317e-008,  2.72806463e-010, -6.00372599e-011,
>   1.04873326e-010, -2.90354939e-010,  1.23198150e-011,  4.51089185e-011,
>   1.53961278e-008, -2.84534138e-008, -1.47669656e-007, -9.56237330e-011,
>   1.34949981e-007,  1.35365215e-008,  1.05462962e-010,  1.22000253e-008,
>   5.26675345e-008,  1.61468061e-013,  1.15773780e-004,  1.13316500e+000,
>  -2.08978438e-001,  1.71734736e-003, -6.11393371e-003,  1.01422014e-003,
>  -2.34079000e-004, -7.68182895e-004,  4.30410613e-005,  1.39548628e-006,
>  -5.94073396e-006,  2.54841049e-006, -2.08469415e-005,  8.27463045e-007,
>  -1.61299771e-007, -1.13106539e-007, -1.91099186e-007,  2.02988954e-007,
>   2.84185372e-007,  1.13675206e-009,  1.00000000e+000,  4.57922050e-008,
>  -3.18780235e-008,  4.01645666e-008,  2.01764619e-010,  3.30927113e-010,
>  -4.97126068e-011, -1.45802125e-011,  1.04104399e-010, -4.09708010e-011,
>   3.62281179e-008, -8.66898323e-008,  7.81101230e-009, -2.49142912e-009,
>   1.01867875e-007, -1.29017612e-008,  2.75718351e-009, -8.99227287e-008,
>  -1.00789879e-008, -3.12095953e-010,  0.00000000e+000,  0.00000000e+000,
>   1.00000000e+000}

![APTK input](https://github.com/user-attachments/assets/3842b662-64ed-42de-87df-3c6f9474276e)
![APTK output](https://github.com/user-attachments/assets/95d14075-4d54-4ab3-b6ec-4ba73ebf8808)

**Comment by eMandanici** [comment] 2024-07-30 08:54
Thank you very much for the prompt reply. 

I tried downloading again the HDF files and reinstall the toolkit but the result is the same. Nothing is generated in the output folder. Here the settings: 
![Screenshot 2024-07-30 104630](https://github.com/user-attachments/assets/258a307d-ce10-4c11-92ed-ee9e0f3a7a68)

I tried both ENVI 6.0 and ENVI Classic 5.6.3. Unfortunately, I cannot downgrade to 5.0 because they changed the license manager.

If it may help, I tried running ENVI Classic from IDL and this is the full error string prompted:

% Attempt to subscript COEFFS with <LONG     (           1)> is out of range.
% Execution halted at: CONVERT_ASTER_L2 1124 
%                      APTK_EVENT       2711 
%                      WIDGET_PROCESS_EVENTS
%                      $MAIN$          
ENVI> 

Thanks again for your help.

**Comment by dawhite** [comment] 2024-07-30 23:01
That does help quite a bit, actually. That portion of the APTK code is where I'm doing some satellite position calculations and is IDL-only, so this is likely not an ENVI issue. APTK is trying (and apparently failing) to extract some information from the L1A file. I can process that file just fine on my end, so I am not sure what is happening. If you open the L1A file in HDF View and navigate to VNIR/VNIR_Band2/Data Fields section, do you see a dataset called "SatellitePosition"? If so, when you click on it, does a table with three columns and multiple rows pop up? It should look like this:

![image](https://github.com/user-attachments/assets/24ac22bb-e6fa-4a0a-8ff9-5dba5b0e2b8e)

**Comment by eMandanici** [comment] 2024-07-31 08:45
I checked and I can see the same table:

![Screenshot 2024-07-31 102552](https://github.com/user-attachments/assets/956fa347-c66b-4408-a83a-4aab2577e732)

Furthermore, the processing of the L1A itself, also with band alignment option, works perfectly.

I also checked if your procedure was overwritten by another one, but it does not seem the case:
ENVI> src = routine_info('CONVERT_ASTER_L2', /source)
ENVI> help, src
** Structure <5a3f1ad0>, 2 tags, length=32, data length=32, refs=1:
   NAME            STRING    'CONVERT_ASTER_L2'
   PATH            STRING    'C:\Program Files\NV5\ENVI60\extensions\aptk.sav'

Thank you.

**Comment by eMandanici** [comment] 2024-07-31 15:44
I resumed an old pc and finally manage to make a test on version 5.0 Classic. I can confirm that in that version APTK works fine. So, probably, it is an issue related to newer ENVI versions.

**Comment by dawhite** [comment] 2024-07-31 21:30
Thank you for this information. I will reach out to the ENVI folks to see if I can get this tested in 6.0. I suspect that the issue is with an IDL update, but either way I'd like to get this resolved for you as soon as possible.

**Comment by eMandanici** [comment] 2024-08-01 07:53
Thank you very much!

**Comment by dawhite** [comment] 2024-08-06 03:07
Just a quick note to say that I'm still working with the ENVI folks on getting this tested in 6.0. Might take a few more days.

**Comment by dawhite** [comment] 2024-08-09 02:37
I was able to run APTK in 6.0 today and experienced the same issue. I traced it to one of IDL's fitting routines, which is behaving a bit differently now and doesn't like how I'm asking it to solve a specific problem. I have a solution. I'll try to test it tomorrow and if it passes, I'll post a new version of APTK this weekend.

**Comment by eMandanici** [comment] 2024-08-09 13:05
Thanks! Happy to see you quickly identify the problem. No rush, anyway! 
I had the issue in ENVI 5.6.3 too, so that IDL routine was modified in an earlier version, I suppose.

**Comment by dawhite** [comment] 2024-08-09 19:42
Tested the solution in 5.0 and 6.0, and in both ENVI and ENVI Classic. Appears to now be working for the dataset you provided. You can get the new version here: https://github.com/dawhite/APTK/releases/tag/v1.1.3. Please let me know if it doesn't work for you.

**Comment by eMandanici** [comment] 2024-08-10 10:20
Thanks a lot! I tested it on ENVI 6.0 and ENVI Classic 5.6.3 and it works perfectly.

**Comment by dawhite** [comment] 2024-08-10 15:17
Excellent! I'll close this issue for now. On related note, though, I observed that the L1A dataset you provided for testing contained about one tenth of the normal amount of satellite position metadata (13 observations instead of 100+). APTK uses that metadata to build the sensor model (RPCs), which involves fitting those observations to polynomials. When there are so few available, the IDL fitting routines will now complain in a way that they did not in the past, which is what produced the error you encountered. The output appears to be fine, but my hope is that the sparse observation issue is a rare occurrence and does not reflect how NASA is routinely generating products these days. I will try to grab some L1A files from different times and locations and see if there is a trend.

**Closed as completed by dawhite** 2024-08-10 15:17 UTC

**Comment by eMandanici** [comment] 2024-08-12 10:15
In the six L1A images I collected for my work, the pattern is the same: 13 obs for VNIR (a bit more for the backward band), 107 obs for the SWIR and 12 obs for TIR. However, they are all on the same path.

**Comment by dawhite** [comment] 2024-08-17 21:36
Thank you for checking. I looked at several recent images as well as some from many years ago that I happened to have in my archive. The same pattern is there. I was probably thinking of the SWIR dataset and forgot that the VNIR is more sparse. The solution I developed has been stable for all of these years, so I guess everything is fine. Let me know if you run into any more issues.
