### ISSUE TITLE
ENVI Crashes when processing TIR only level 1a and level1b files

### ISSUE THREAD

**Issue by TalfanBarnie** [dawhite/APTK#1] opened 2016-05-16 22:47 UTC
Hello dawhite,

When I try to process TIR only level1a or level 1b ASTER HDF EOS files I get the error:

"Attempt to subscript WHERE_D2 with <LONG  (       2)> is out of range"

ENVI then exits. This happens both in 'ENVI classic' and the new version. Changing the default processing options gives the same error. FIles with VNIR + SWIR + TIR images process without trouble. I'm running APTK 1.0.2, ENVI 5.2 64 bit, WIndows 7 Enterprise with Service Pack 1

Many thanks!

**Comment by TalfanBarnie** [comment] 2016-05-18 10:03
...actually it only crashes for TIR only level 1B files. Level 1A process fine, my mistake. Unfortunately it's the level 1B RPCs I'm after...

**Comment by dawhite** [comment] 2016-05-18 11:03
Very strange.  Can you send me the exact filename for the L1B dataset?  I will pull it down from the archive and look into this.  It might take me a day or two.

**Comment by TalfanBarnie** [comment] 2016-05-18 12:08
This is the full name of the file I ordered from Reverb:

AST_L1B_00301012015032416_20160516112533_1666.hdf

Thanks for your help!

**Comment by dawhite** [comment] 2016-05-19 03:02
That helped a lot--thank you.  I was able to reproduce the error and can see why it is happening.  Fixing it will likely take a few days since I work on these plugins in my spare time and this is a non-trivial issue.

**Comment by dawhite** [comment] 2016-05-22 13:14
Issue is now fixed.  I pushed a new release (v1.0.3) that you can download: https://github.com/dawhite/APTK/releases/tag/v1.0.3

**Comment by TalfanBarnie** [comment] 2016-05-23 09:23
That works for me too - many thanks for fixing this so quickly.

**Closed as completed** 2016-05-23 10:09 UTC
